project:
  type: website

website:
  title: "Архив журнала 'Телескоп'"
  navbar:
    left:
      - href: index.qmd
        text: Выпуски
      - authors.qmd
      - sections.qmd
  page-footer: 
    left: "© 2026, Российский научный журнал «Телескоп: журнал социологических и маркетинговых исследований»" 
    right: 
      - icon: github
        href: https://github.com/constdivis/telescope-old-issues
format:
  html:
    theme: 
      light: yeti
      dark: slate
    css: styles.css
    toc: true
    toc-title: "На этой странице:"




